--- 
before_commands: 
  - "composer install --no-dev --prefer-source"
  - "composer require predis/predis \"~1.1.0\""
  - "composer require mongodb/mongodb \"^1.1\""
  - "composer require phpfastcache/phpssdb ~1.0.0\""
  - "composer require phpfastcache/couchdb \"~1.0.0\""
build: 
  dependencies: 
    before: []
  environment: 
    php: 
      version: 5.6
checks: 
  php: true
coding_style: 
  php: 
    spaces: 
      around_operators: 
        concatenation: true
filter: 
  excluded_paths: 
    - bin/*
    - docs/*
    - examples/*
    - var/*
    - vendor/*
    - tests/*
    - /home/*
tools:
  external_code_coverage: false
  php_code_coverage: true
  php_code_sniffer: 
    config: 
      standard: PSR2
    enabled: true
    filter: 
      paths: 
        - src/*
  php_mess_detector: 
    enabled: true
    filter: 
      paths: 
        - src/*