before_commands:
    - "composer install --no-dev --prefer-source"
    - "composer require predis/predis \"~1.1.0\""
    - "composer require mongodb/mongodb \"^1.1\""
    - "composer require phpfastcache/phpssdb ~1.0.0\""
    - "composer require phpfastcache/couchdb \"~1.0.0\""
filter:
    excluded_paths: ["bin/*", "docs/*", "examples/*", "var/*", "vendor/*", "tests/*"]
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
tools:
    external_code_coverage: false
    php_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
build:
    environment:
        php:
            version: 5.6
    dependencies:
        before:
            - pecl install cassandra