name: PHP Composer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.6.2
        with:
          php-version: '7.3'
          coverage: none
      - uses: niden/actions-memcached@v7
      - uses: actions/checkout@v1
      - uses: zhulik/redis-action@v1.0.0
        with:
          redis version: '5'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
      - name: Run test suite
        run: php -f ./bin/ci/run_tests.php

